name: Update Version File

on:
  push:
    branches:
      - main
    paths:
      - 'tesla.html'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version.txt
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"<% 
      - name: Commit changes
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add version.txt
          git commit -m 'Update version.txt with new modification date'
          git push
